networks:
  # The presence of these objects is sufficient to define them
  expense: {}
volumes:
  mysql:
services:
  backend:
    image: shailaja117/backend:1.0.0
    command: sh -c "sleep 10 && node /opt/backend/index.js"
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql

  # docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: shailaja117/mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql

  frontend:
    image: shailaja117/frontend:1.0.0
    networks:
    - expense
    container_name: frontend
    ports:
    - 80:80
    depends_on:
    - backend
  
  